### ISSUE TITLE
deletes everything from the DeepFaceLabClient folder when i click Install in the Dashboard

### ISSUE THREAD

**Issue by igor-kurenkov** [Lenny4/DeepFaceLabClient#58]
Win 10 x64, Nvidia 3060. 
Starts up fine. Deletes everything from the DeepFaceLabClient folder when i click Install in the Dashboard.
Steps to reproduce^
1. download the release
2. unpack
3. run DeepFaceLabClient.exe
4. specify the installed DeepFaceLab folder. The installation got verified
5. navigate to the Dashboard, click Install
6. Aaaaand it's gone. Deletes itself completely leaving the empty folder
![image](https://github.com/Lenny4/DeepFaceLabClient/assets/82575007/e075daef-ee8c-4c39-a5ea-c9171ed02c4d)

**Comment by Lenny4** [comment]
Should be fix on https://github.com/Lenny4/DeepFaceLabClient/releases/tag/v0.1.2

If not reopen the issue
