### ISSUE TITLE
GPU does not show up in the gui when using deepfacelab dml plugin with nvidia 30 series build on my 5700xt

### ISSUE THREAD

**Issue by Cxsmo-ai** [Lenny4/DeepFaceLabClient#59]
GPU does not show up in the GUI when using the DeepFaceLab DML plugin https://github.com/brucehsu/DeepFaceLab/releases/tag/dml_plugin with the Nvidia 30 series build on my AMD 5700XT. Normally, in the normal cmd deepfacelab 30 series version with the dml plugin, my AMD 5700xt works perfectly. Just in training, it shows dml as the GPU, which is normal for the plugin, but in the GUI, it shows nothing. 
![image](https://github.com/Lenny4/DeepFaceLabClient/assets/74084396/9b677f42-7bbf-42e8-b7c4-1043c83cd242)
this shows driver version and task manager showing gpu and the gui saying no gpu detected.

**Comment by Lenny4** [comment]
Note for dev:

Seems like it's not linked to the plugin [dml_plugin](https://github.com/brucehsu/DeepFaceLab/releases/tag/dml_plugin) but rather the python exec diff between `NVIDIA_RTX3000\python-3.6.8` and `directX12\python-3.6.8`

**Comment by Lenny4** [comment]
@Pickymarker when you use DeepFaceLab **WITHOUT** the client and you run `data_src faceset extract.bat` does DeepFaceLab ask you the question `Choose one or several GPU idx (separated with comma)` ?

If so does it show you your GPU in the available option ?

![Capture](https://github.com/Lenny4/DeepFaceLabClient/assets/25544892/08686b40-157e-4278-929a-11cb06666d47)

**Comment by Lenny4** [comment]
No answer, closing.
