### ISSUE TITLE
Unsolicited emails

### ISSUE THREAD

**Issue by jeanas** [Lenny4/DeepFaceLabClient#68]
In response to

![image](https://github.com/Lenny4/DeepFaceLabClient/assets/37271310/b6220921-9a70-4c51-9772-92fa7a45ded4)

![image](https://github.com/Lenny4/DeepFaceLabClient/assets/37271310/bf8658a5-9f38-4406-b2cb-43b4d3bcbc88)

I do not understand why I was mailed about this project, having no particular interest in deep learning, face swaps or video editing, or relationship with the project or related projects.

Are you “mass mailing” lots of GitHub users? If so, please don't do that. Thanks.

**Comment by Lenny4** [comment]
Hi,
Sorry for the inconvenience.
Won't happen, just wanted to share with people who stared DeepFaceLab

**Comment by aklapper** [comment]
@Lenny4: I did not "star DeepFaceLab" and you sent me unsolicited spam. This is unacceptable behavior.

**Comment by Lenny4** [comment]
@aklapper

I anderstand I didn't mean to bother you it won't happen again.

**Comment by arkid15r** [comment]
Hey, you should stop doing that. 
Please do.

**Comment by Lenny4** [comment]
Hi,
Yes it won't happen again.

**Comment by Lenny4** [comment]
https://github.com/Lenny4/DeepFaceLabClient/issues/69
