### ISSUE TITLE
unrecognized arguments: --include-audio

### ISSUE THREAD

**Issue by SamuraiBUPT** [Lenny4/DeepFaceLabClient#71]
Hello, when I press the `To Video` -> `Create MP4` button, the terminal got error report: 
```
main.py: error: unrecognized arguments: --include-audio
```

don't know how to fix it

**DeepFaceLabClient-windows-v0.3.0** here.

**Comment by Lenny4** [comment]
Hi @SamuraiBUPT, can you try to run the command directly with DeepFaceLab (without DeepFaceLabClient) and tell me if you still got the error ?

**Comment by SamuraiBUPT** [comment]
Took your advice, the `merge Quick96.bat` reports that `CUDA OUT OF MEMORY`, it seems that my VMEM is small for merging. I will try switch to another one with larger VMEM, thanks!
